version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain Python dependencies (Server & Agent)
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/agent"
    schedule:
      interval: "weekly"
