blank_issues_enabled: false
contact_links:
  - name: Community Discussions & Support
    url: https://discord.gg/redshadows
    about: Please ask questions and get support on our Discord server.
  - name: Security Vulnerabilities
    url: mailto:security@redshadows.org
    about: Privately report security concerns directly to the maintainers.
