name: Draft Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  draft-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Release Notes & Draft
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
          files: |
            README.md
            README_AR.md
            LICENSE
            CHANGELOG.md
            docs/*
